server:
  port: 9000
spring:
  application:
    name: flight-catering
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: json
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
  datasource:
    url: jdbc:postgresql://db:5432/catering
    username: compose-postgres
    password: compose-postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate.ddl-auto: update
  mail:
    host: smtp.mail.ru
    username: aiva-project-send@mail.ru
    password: jVZmiiwFusDCTg0S1FsH
    port: 465
    protocol: smtps
    debug: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/