server:
  port: 9001
spring:
  application:
    name: flight-order
  datasource:
    driver-class-name: org.postgresql.Driver
    username: compose-postgres
    url: jdbc:postgresql://db:5432/flight
    password: compose-postgres
  flyway:
    schemas: order
  jpa:
    properties:
      hibernate:
        default_schema: order
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'true'
    hibernate:
      ddl-auto: validate
  kafka:
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
