server:
  port: 9000
spring:
  application:
    name: flight-catering
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: json
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
  datasource:
    driver-class-name: org.postgresql.Driver
    username: compose-postgres
    url: jdbc:postgresql://localhost:5432/flight
    password: compose-postgres
  flyway:
    schemas: catering
  jpa:
    properties:
      hibernate:
        default_schema: catering
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'true'
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.mail.ru
    username: aiva-project-send@mail.ru
    password: jVZmiiwFusDCTg0S1FsH
    port: 465
    protocol: smtps
    debug: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/