spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: compose-postgres
    url: jdbc:postgresql://db:5432/flight
    password: compose-postgres
  flyway:
    schemas: users
  jpa:
    properties:
      hibernate:
        default_schema: users
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'true'
    hibernate:
      ddl-auto: validate
server:
  port: '9002'

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/